### ISSUE TITLE
Open the plugin page with 500 error 

### ISSUE THREAD

**Issue by archonwang** [r-schmidtke/featureview#1]
please check it, Thanks.

```
Started GET "/featureview?project_id=uth_testteam" for 192.168.20.231 at 2017-07-08 19:32:22 +0800
Processing by FeatureviewController#index as HTML
  Parameters: {"project_id"=>"uth_testteam"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 3.5ms)

NoMethodError (undefined method `id' for nil:NilClass):
  plugins/featureview/app/controllers/featureview_controller.rb:7:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/featureview?project_id=uth_testteam" for 192.168.20.231 at 2017-07-08 19:32:22 +0800
Processing by FeatureviewController#index as */*
  Parameters: {"project_id"=>"uth_testteam"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.2ms)

NoMethodError (undefined method `id' for nil:NilClass):
  plugins/featureview/app/controllers/featureview_controller.rb:7:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by archonwang** [comment]
@r-schmidtke ,
error log, please help to check.

```
Started GET "/featureview?project_id=demo" for 192.168.60.238 at 2018-01-12 11:17:13 +0800
Processing by FeatureviewController#index as HTML
  Parameters: {"project_id"=>"demo"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 3.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.9ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (4.0ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.7ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (172.2ms)

ArgumentError (Malformed version number string DemoVersion 演示版本):
  plugins/featureview/app/controllers/featureview_controller.rb:55:in `block in select_versions'
  plugins/featureview/app/controllers/featureview_controller.rb:55:in `each'
  plugins/featureview/app/controllers/featureview_controller.rb:55:in `sort_by'
  plugins/featureview/app/controllers/featureview_controller.rb:55:in `select_versions'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```
